### ISSUE TITLE
Invetica specs are open source

### ISSUE THREAD

**Issue by jcf** [ioRekz/spectator#3]
I don’t know if it helps, but I’ve open sourced some of the work I’ve done writing specs and using for work and fun.

There’s some stuff under the Invetica org, and I have a couple of personal things too. Feel free to ask questions and/or link to stuff.

Also, Arachne, ring, Onyx, clojure.core all have specs. I’ve also found a couple of libraries that aim to spec Datomic. Not sure if they’re already listed.

**Comment by jcf** [comment]
Came here from [this conversation](https://reddit.com/r/Clojure/comments/7qlwmo/a_spec_for_urls_in_clojure/) with @yogthos over on Reddit.

**Comment by ioRekz** [comment]
Thanks that helps, I'm adding media-types and uri. Did I miss some ?

ring and clojure.core specs are already in the list. 
I will go look for Arachne now.

I did look at Onyx and I think the clojure specs will be in the next version. Not yet on master at least.

Do you have links to the lib that aim to spec datomic ?

**Comment by ioRekz** [comment]
ok find it https://github.com/alexanderkiel/datomic-spec
